# Generated by Django 3.2.7 on 2022-04-06 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='result_In_Percentage',
        ),
        migrations.AddField(
            model_name='research',
            name='result',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
