# Generated by Django 3.2.7 on 2022-04-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_auto_20220406_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
