# Generated by Django 3.2.7 on 2022-04-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_research_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
