# Generated by Django 4.1 on 2022-10-01 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='account_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
